-- 자동 생성: collect_freight_index.py --sql (14행)
insert into public.freight_index (index_code, route, value, prev_value, pct_change, pub_date) values ('SCFI', 'COMPOSITE', 3062.95, 3080.31, -0.56, '2026-07-24') on conflict (index_code, route, pub_date) do update set value=excluded.value, prev_value=excluded.prev_value, pct_change=excluded.pct_change, updated_at=now();
insert into public.freight_index (index_code, route, value, prev_value, pct_change, pub_date) values ('CCFI', 'COMPOSITE', 1901.27, 1910.67, -0.49, '2026-07-24') on conflict (index_code, route, pub_date) do update set value=excluded.value, prev_value=excluded.prev_value, pct_change=excluded.pct_change, updated_at=now();
insert into public.freight_index (index_code, route, value, prev_value, pct_change, pub_date) values ('CCFI', 'JAPAN', 925.31, 942.32, -1.81, '2026-07-24') on conflict (index_code, route, pub_date) do update set value=excluded.value, prev_value=excluded.prev_value, pct_change=excluded.pct_change, updated_at=now();
insert into public.freight_index (index_code, route, value, prev_value, pct_change, pub_date) values ('CCFI', 'EUROPE', 2483.29, 2506.94, -0.94, '2026-07-24') on conflict (index_code, route, pub_date) do update set value=excluded.value, prev_value=excluded.prev_value, pct_change=excluded.pct_change, updated_at=now();
insert into public.freight_index (index_code, route, value, prev_value, pct_change, pub_date) values ('CCFI', 'W/C AMERICA', 1632.4, 1559.94, 4.65, '2026-07-24') on conflict (index_code, route, pub_date) do update set value=excluded.value, prev_value=excluded.prev_value, pct_change=excluded.pct_change, updated_at=now();
insert into public.freight_index (index_code, route, value, prev_value, pct_change, pub_date) values ('CCFI', 'E/C AMERICA', 1770.25, 1778.34, -0.45, '2026-07-24') on conflict (index_code, route, pub_date) do update set value=excluded.value, prev_value=excluded.prev_value, pct_change=excluded.pct_change, updated_at=now();
insert into public.freight_index (index_code, route, value, prev_value, pct_change, pub_date) values ('CCFI', 'KOREA', 664.02, 636.59, 4.31, '2026-07-24') on conflict (index_code, route, pub_date) do update set value=excluded.value, prev_value=excluded.prev_value, pct_change=excluded.pct_change, updated_at=now();
insert into public.freight_index (index_code, route, value, prev_value, pct_change, pub_date) values ('CCFI', 'SOUTHEAST', 1074.12, 1146.43, -6.31, '2026-07-24') on conflict (index_code, route, pub_date) do update set value=excluded.value, prev_value=excluded.prev_value, pct_change=excluded.pct_change, updated_at=now();
insert into public.freight_index (index_code, route, value, prev_value, pct_change, pub_date) values ('CCFI', 'MEDITERRANEAN', 3282.78, 3153.87, 4.09, '2026-07-24') on conflict (index_code, route, pub_date) do update set value=excluded.value, prev_value=excluded.prev_value, pct_change=excluded.pct_change, updated_at=now();
insert into public.freight_index (index_code, route, value, prev_value, pct_change, pub_date) values ('CCFI', 'AUSTRALIA/NEW ZEALAND', 1517.53, 1530.43, -0.84, '2026-07-24') on conflict (index_code, route, pub_date) do update set value=excluded.value, prev_value=excluded.prev_value, pct_change=excluded.pct_change, updated_at=now();
insert into public.freight_index (index_code, route, value, prev_value, pct_change, pub_date) values ('CCFI', 'SOUTH AFRICA', 1388.64, 1443.87, -3.83, '2026-07-24') on conflict (index_code, route, pub_date) do update set value=excluded.value, prev_value=excluded.prev_value, pct_change=excluded.pct_change, updated_at=now();
insert into public.freight_index (index_code, route, value, prev_value, pct_change, pub_date) values ('CCFI', 'SOUTH AMERICA', 1467.82, 1545.14, -5.0, '2026-07-24') on conflict (index_code, route, pub_date) do update set value=excluded.value, prev_value=excluded.prev_value, pct_change=excluded.pct_change, updated_at=now();
insert into public.freight_index (index_code, route, value, prev_value, pct_change, pub_date) values ('CCFI', 'WEST EAST AFRICA', 1191.21, 1188.86, 0.2, '2026-07-24') on conflict (index_code, route, pub_date) do update set value=excluded.value, prev_value=excluded.prev_value, pct_change=excluded.pct_change, updated_at=now();
insert into public.freight_index (index_code, route, value, prev_value, pct_change, pub_date) values ('CCFI', 'PERSIAN GULF/RED SEA', 2971.65, 3180.09, -6.55, '2026-07-24') on conflict (index_code, route, pub_date) do update set value=excluded.value, prev_value=excluded.prev_value, pct_change=excluded.pct_change, updated_at=now();