/* 주요 포트 UN/LOCODE (en 소문자 → LOCODE) + 국가 한글 (FR-01 포트 검색용) */
export const LOCODE: Record<string, string> = {
  'shanghai': 'CNSHA', 'ningbo': 'CNNGB', 'shenzhen (yantian)': 'CNYTN', 'guangzhou (nansha)': 'CNGZG',
  'qingdao': 'CNTAO', 'tianjin': 'CNTXG', 'xiamen': 'CNXMN', 'dalian': 'CNDLC', 'hong kong': 'HKHKG',
  'kaohsiung': 'TWKHH', 'busan': 'KRPUS', 'incheon': 'KRINC', 'gwangyang': 'KRKAN',
  'tokyo': 'JPTYO', 'yokohama': 'JPYOK', 'nagoya': 'JPNGO', 'kobe': 'JPUKB', 'singapore': 'SGSIN',
  'tanjung pelepas': 'MYTPP', 'port klang': 'MYPKG', 'penang': 'MYPEN', 'kuching': 'MYKCH',
  'jakarta (tg. priok)': 'IDJKT', 'surabaya': 'IDSUB', 'laem chabang': 'THLCH', 'bangkok': 'THBKK',
  'ho chi minh (cat lai)': 'VNSGN', 'cai mep': 'VNCMT', 'haiphong': 'VNHPH', 'manila': 'PHMNL',
  'yangon': 'MMRGN', 'sihanoukville': 'KHKOS', 'colombo': 'LKCMB', 'chattogram': 'BDCGP',
  'nhava sheva (jnpt)': 'INNSA', 'mundra': 'INMUN', 'chennai': 'INMAA', 'karachi': 'PKKHI',
  'jebel ali': 'AEJEA', 'khalifa (abu dhabi)': 'AEKHL', 'hamad': 'QAHMD', 'dammam': 'SADMM',
  'jeddah': 'SAJED', 'salalah': 'OMSLL', 'bandar abbas': 'IRBND', 'rotterdam': 'NLRTM',
  'antwerp-bruges': 'BEANR', 'hamburg': 'DEHAM', 'bremerhaven': 'DEBRV', 'le havre': 'FRLEH',
  'fos-marseille': 'FRFOS', 'valencia': 'ESVLC', 'algeciras': 'ESALG', 'barcelona': 'ESBCN',
  'genoa': 'ITGOA', 'gioia tauro': 'ITGIT', 'trieste': 'ITTRS', 'koper': 'SIKOP', 'piraeus': 'GRPIR',
  'ambarli (istanbul)': 'TRAMB', 'mersin': 'TRMER', 'gdansk': 'PLGDN', 'felixstowe': 'GBFXT',
  'london gateway': 'GBLGP', 'los angeles': 'USLAX', 'long beach': 'USLGB', 'oakland': 'USOAK',
  'seattle-tacoma': 'USSEA', 'vancouver': 'CAVAN', 'new york/new jersey': 'USNYC', 'savannah': 'USSAV',
  'charleston': 'USCHS', 'houston': 'USHOU', 'manzanillo (mx)': 'MXZLO', 'lazaro cardenas': 'MXLZC',
  'santos': 'BRSSZ', 'callao': 'PECLL', 'cartagena': 'COCTG', 'colon (panama)': 'PACOL',
  'buenos aires': 'ARBUE', 'guayaquil': 'ECGYE', 'tanger med': 'MAPTM', 'port said': 'EGPSD',
  'alexandria': 'EGALY', 'durban': 'ZADUR', 'cape town': 'ZACPT', 'lagos (apapa)': 'NGLOS',
  'mombasa': 'KEMBA', 'dar es salaam': 'TZDAR', 'sydney (botany)': 'AUSYD', 'melbourne': 'AUMEL',
  'brisbane': 'AUBNE', 'auckland': 'NZAKL',
};
export const CC_KO: Record<string, string> = {
  KR: '한국', CN: '중국', JP: '일본', HK: '홍콩', TW: '대만', SG: '싱가포르', MY: '말레이시아', ID: '인도네시아',
  TH: '태국', VN: '베트남', PH: '필리핀', MM: '미얀마', KH: '캄보디아', LK: '스리랑카', BD: '방글라데시', IN: '인도',
  PK: '파키스탄', AE: 'UAE', QA: '카타르', SA: '사우디', OM: '오만', IR: '이란', NL: '네덜란드', BE: '벨기에',
  DE: '독일', FR: '프랑스', ES: '스페인', IT: '이탈리아', SI: '슬로베니아', GR: '그리스', TR: '튀르키예', PL: '폴란드',
  GB: '영국', US: '미국', CA: '캐나다', MX: '멕시코', BR: '브라질', PE: '페루', CO: '콜롬비아', PA: '파나마',
  AR: '아르헨티나', EC: '에콰도르', MA: '모로코', EG: '이집트', ZA: '남아공', NG: '나이지리아', KE: '케냐', TZ: '탄자니아',
  AU: '호주', NZ: '뉴질랜드',
};
