-- 자동 생성: collect_portinsight_api.py --sql (IMF PortWatch, 기준일 2026-07-17, 93개 항만)
update public.pi_ports set tpfs=8.4, delay_h=1.2, waiting_cnt=0, berthed_cnt=59, updated_at=now() where name_en='Shanghai';
update public.pi_ports set tpfs=15.3, delay_h=2.9, waiting_cnt=0, berthed_cnt=40, updated_at=now() where name_en='Ningbo';
update public.pi_ports set tpfs=36.0, delay_h=10.4, waiting_cnt=0, berthed_cnt=11, updated_at=now() where name_en='Shenzhen (Yantian)';
update public.pi_ports set tpfs=12.0, delay_h=2.0, waiting_cnt=0, berthed_cnt=27, updated_at=now() where name_en='Guangzhou (Nansha)';
update public.pi_ports set tpfs=33.1, delay_h=9.1, waiting_cnt=0, berthed_cnt=26, updated_at=now() where name_en='Qingdao';
update public.pi_ports set tpfs=7.2, delay_h=0.9, waiting_cnt=0, berthed_cnt=27, updated_at=now() where name_en='Tianjin';
update public.pi_ports set tpfs=58.2, delay_h=21.3, waiting_cnt=1, berthed_cnt=21, updated_at=now() where name_en='Xiamen';
update public.pi_ports set tpfs=7.2, delay_h=0.9, waiting_cnt=0, berthed_cnt=14, updated_at=now() where name_en='Dalian';
update public.pi_ports set tpfs=5.3, delay_h=0.6, waiting_cnt=0, berthed_cnt=34, updated_at=now() where name_en='Hong Kong';
update public.pi_ports set tpfs=81.6, delay_h=35.4, waiting_cnt=8, berthed_cnt=31, updated_at=now() where name_en='Kaohsiung';
update public.pi_ports set tpfs=7.2, delay_h=0.9, waiting_cnt=14, berthed_cnt=15, updated_at=now() where name_en='Busan';
update public.pi_ports set tpfs=47.5, delay_h=15.7, waiting_cnt=7, berthed_cnt=2, updated_at=now() where name_en='Incheon';
update public.pi_ports set tpfs=30.1, delay_h=7.9, waiting_cnt=4, berthed_cnt=1, updated_at=now() where name_en='Gwangyang';
update public.pi_ports set tpfs=17.2, delay_h=3.4, waiting_cnt=0, berthed_cnt=23, updated_at=now() where name_en='Tokyo';
update public.pi_ports set tpfs=36.2, delay_h=10.5, waiting_cnt=0, berthed_cnt=37, updated_at=now() where name_en='Yokohama';
update public.pi_ports set tpfs=38.4, delay_h=11.4, waiting_cnt=0, berthed_cnt=44, updated_at=now() where name_en='Nagoya';
update public.pi_ports set tpfs=10.7, delay_h=1.7, waiting_cnt=0, berthed_cnt=27, updated_at=now() where name_en='Kobe';
update public.pi_ports set tpfs=30.0, delay_h=7.9, waiting_cnt=0, berthed_cnt=123, updated_at=now() where name_en='Singapore';
update public.pi_ports set tpfs=23.1, delay_h=5.3, waiting_cnt=0, berthed_cnt=12, updated_at=now() where name_en='Tanjung Pelepas';
update public.pi_ports set tpfs=15.2, delay_h=2.8, waiting_cnt=0, berthed_cnt=30, updated_at=now() where name_en='Port Klang';
update public.pi_ports set tpfs=24.4, delay_h=5.8, waiting_cnt=0, berthed_cnt=4, updated_at=now() where name_en='Penang';
update public.pi_ports set tpfs=66.4, delay_h=26.0, waiting_cnt=0, berthed_cnt=3, updated_at=now() where name_en='Kuching';
update public.pi_ports set tpfs=77.0, delay_h=32.4, waiting_cnt=6, berthed_cnt=28, updated_at=now() where name_en='Jakarta (Tg. Priok)';
update public.pi_ports set tpfs=69.5, delay_h=27.8, waiting_cnt=3, berthed_cnt=18, updated_at=now() where name_en='Surabaya';
update public.pi_ports set tpfs=20.9, delay_h=4.6, waiting_cnt=0, berthed_cnt=19, updated_at=now() where name_en='Laem Chabang';
update public.pi_ports set tpfs=36.7, delay_h=10.7, waiting_cnt=0, berthed_cnt=18, updated_at=now() where name_en='Bangkok';
update public.pi_ports set tpfs=4.0, delay_h=0.4, waiting_cnt=0, berthed_cnt=10, updated_at=now() where name_en='Ho Chi Minh (Cat Lai)';
update public.pi_ports set tpfs=38.8, delay_h=11.6, waiting_cnt=0, berthed_cnt=16, updated_at=now() where name_en='Cai Mep';
update public.pi_ports set tpfs=11.6, delay_h=1.9, waiting_cnt=0, berthed_cnt=19, updated_at=now() where name_en='Haiphong';
update public.pi_ports set tpfs=45.0, delay_h=14.5, waiting_cnt=0, berthed_cnt=19, updated_at=now() where name_en='Manila';
update public.pi_ports set tpfs=33.1, delay_h=9.1, waiting_cnt=0, berthed_cnt=3, updated_at=now() where name_en='Yangon';
update public.pi_ports set tpfs=7.4, delay_h=1.0, waiting_cnt=0, berthed_cnt=3, updated_at=now() where name_en='Sihanoukville';
update public.pi_ports set tpfs=61.5, delay_h=23.2, waiting_cnt=1, berthed_cnt=12, updated_at=now() where name_en='Colombo';
update public.pi_ports set tpfs=41.4, delay_h=12.8, waiting_cnt=0, berthed_cnt=6, updated_at=now() where name_en='Chattogram';
update public.pi_ports set tpfs=62.5, delay_h=23.7, waiting_cnt=2, berthed_cnt=24, updated_at=now() where name_en='Nhava Sheva (JNPT)';
update public.pi_ports set tpfs=40.0, delay_h=12.1, waiting_cnt=0, berthed_cnt=10, updated_at=now() where name_en='Mundra';
update public.pi_ports set tpfs=51.6, delay_h=17.8, waiting_cnt=0, berthed_cnt=4, updated_at=now() where name_en='Chennai';
update public.pi_ports set tpfs=81.9, delay_h=35.6, waiting_cnt=2, berthed_cnt=6, updated_at=now() where name_en='Karachi';
update public.pi_ports set tpfs=74.4, delay_h=30.8, waiting_cnt=1, berthed_cnt=6, updated_at=now() where name_en='Jebel Ali';
update public.pi_ports set tpfs=87.5, delay_h=39.3, waiting_cnt=1, berthed_cnt=2, updated_at=now() where name_en='Khalifa (Abu Dhabi)';
update public.pi_ports set tpfs=73.6, delay_h=30.3, waiting_cnt=0, berthed_cnt=2, updated_at=now() where name_en='Hamad';
update public.pi_ports set tpfs=11.4, delay_h=1.8, waiting_cnt=0, berthed_cnt=1, updated_at=now() where name_en='Dammam';
update public.pi_ports set tpfs=26.4, delay_h=6.5, waiting_cnt=0, berthed_cnt=8, updated_at=now() where name_en='Jeddah';
update public.pi_ports set tpfs=36.3, delay_h=10.5, waiting_cnt=0, berthed_cnt=5, updated_at=now() where name_en='Salalah';
update public.pi_ports set tpfs=38.8, delay_h=11.6, waiting_cnt=0, berthed_cnt=1, updated_at=now() where name_en='Bandar Abbas';
update public.pi_ports set tpfs=73.3, delay_h=30.1, waiting_cnt=16, berthed_cnt=87, updated_at=now() where name_en='Rotterdam';
update public.pi_ports set tpfs=18.1, delay_h=3.7, waiting_cnt=0, berthed_cnt=52, updated_at=now() where name_en='Antwerp-Bruges';
update public.pi_ports set tpfs=22.7, delay_h=5.2, waiting_cnt=0, berthed_cnt=16, updated_at=now() where name_en='Hamburg';
update public.pi_ports set tpfs=37.6, delay_h=11.1, waiting_cnt=0, berthed_cnt=12, updated_at=now() where name_en='Bremerhaven';
update public.pi_ports set tpfs=14.2, delay_h=2.6, waiting_cnt=0, berthed_cnt=9, updated_at=now() where name_en='Le Havre';
update public.pi_ports set tpfs=30.3, delay_h=8.0, waiting_cnt=0, berthed_cnt=4, updated_at=now() where name_en='Fos-Marseille';
update public.pi_ports set tpfs=11.4, delay_h=1.8, waiting_cnt=0, berthed_cnt=9, updated_at=now() where name_en='Valencia';
update public.pi_ports set tpfs=29.2, delay_h=7.6, waiting_cnt=0, berthed_cnt=16, updated_at=now() where name_en='Algeciras';
update public.pi_ports set tpfs=25.4, delay_h=6.1, waiting_cnt=0, berthed_cnt=11, updated_at=now() where name_en='Barcelona';
update public.pi_ports set tpfs=21.7, delay_h=4.9, waiting_cnt=0, berthed_cnt=8, updated_at=now() where name_en='Genoa';
update public.pi_ports set tpfs=88.0, delay_h=39.6, waiting_cnt=2, berthed_cnt=7, updated_at=now() where name_en='Gioia Tauro';
update public.pi_ports set tpfs=59.3, delay_h=21.9, waiting_cnt=0, berthed_cnt=5, updated_at=now() where name_en='Trieste';
update public.pi_ports set tpfs=12.8, delay_h=2.2, waiting_cnt=0, berthed_cnt=3, updated_at=now() where name_en='Koper';
update public.pi_ports set tpfs=46.1, delay_h=15.0, waiting_cnt=0, berthed_cnt=14, updated_at=now() where name_en='Piraeus';
update public.pi_ports set tpfs=53.9, delay_h=19.0, waiting_cnt=0, berthed_cnt=11, updated_at=now() where name_en='Ambarli (Istanbul)';
update public.pi_ports set tpfs=75.0, delay_h=31.2, waiting_cnt=2, berthed_cnt=9, updated_at=now() where name_en='Mersin';
update public.pi_ports set tpfs=54.3, delay_h=19.2, waiting_cnt=0, berthed_cnt=9, updated_at=now() where name_en='Gdansk';
update public.pi_ports set tpfs=28.7, delay_h=7.4, waiting_cnt=0, berthed_cnt=3, updated_at=now() where name_en='Felixstowe';
update public.pi_ports set tpfs=27.2, delay_h=6.8, waiting_cnt=0, berthed_cnt=6, updated_at=now() where name_en='London Gateway';
update public.pi_ports set tpfs=26.1, delay_h=6.4, waiting_cnt=0, berthed_cnt=10, updated_at=now() where name_en='Los Angeles';
update public.pi_ports set tpfs=26.1, delay_h=6.4, waiting_cnt=0, berthed_cnt=10, updated_at=now() where name_en='Long Beach';
update public.pi_ports set tpfs=31.9, delay_h=8.6, waiting_cnt=0, berthed_cnt=2, updated_at=now() where name_en='Oakland';
update public.pi_ports set tpfs=52.3, delay_h=18.2, waiting_cnt=0, berthed_cnt=1, updated_at=now() where name_en='Seattle-Tacoma';
update public.pi_ports set tpfs=36.2, delay_h=10.5, waiting_cnt=0, berthed_cnt=6, updated_at=now() where name_en='Vancouver';
update public.pi_ports set tpfs=47.4, delay_h=15.7, waiting_cnt=0, berthed_cnt=10, updated_at=now() where name_en='New York/New Jersey';
update public.pi_ports set tpfs=34.0, delay_h=9.5, waiting_cnt=0, berthed_cnt=6, updated_at=now() where name_en='Savannah';
update public.pi_ports set tpfs=59.4, delay_h=22.0, waiting_cnt=0, berthed_cnt=5, updated_at=now() where name_en='Charleston';
update public.pi_ports set tpfs=16.3, delay_h=3.2, waiting_cnt=0, berthed_cnt=19, updated_at=now() where name_en='Houston';
update public.pi_ports set tpfs=63.6, delay_h=24.3, waiting_cnt=1, berthed_cnt=5, updated_at=now() where name_en='Manzanillo (MX)';
update public.pi_ports set tpfs=19.3, delay_h=4.1, waiting_cnt=0, berthed_cnt=4, updated_at=now() where name_en='Lazaro Cardenas';
update public.pi_ports set tpfs=90.5, delay_h=41.3, waiting_cnt=6, berthed_cnt=18, updated_at=now() where name_en='Santos';
update public.pi_ports set tpfs=56.9, delay_h=20.6, waiting_cnt=0, berthed_cnt=6, updated_at=now() where name_en='Callao';
update public.pi_ports set tpfs=65.3, delay_h=25.3, waiting_cnt=1, berthed_cnt=11, updated_at=now() where name_en='Cartagena';
update public.pi_ports set tpfs=53.6, delay_h=18.8, waiting_cnt=0, berthed_cnt=3, updated_at=now() where name_en='Colon (Panama)';
update public.pi_ports set tpfs=11.3, delay_h=1.8, waiting_cnt=0, berthed_cnt=3, updated_at=now() where name_en='Buenos Aires';
update public.pi_ports set tpfs=78.1, delay_h=33.1, waiting_cnt=1, berthed_cnt=6, updated_at=now() where name_en='Guayaquil';
update public.pi_ports set tpfs=53.8, delay_h=18.9, waiting_cnt=0, berthed_cnt=13, updated_at=now() where name_en='Tanger Med';
update public.pi_ports set tpfs=29.3, delay_h=7.6, waiting_cnt=0, berthed_cnt=2, updated_at=now() where name_en='Port Said';
update public.pi_ports set tpfs=14.2, delay_h=2.6, waiting_cnt=0, berthed_cnt=8, updated_at=now() where name_en='Alexandria';
update public.pi_ports set tpfs=42.9, delay_h=13.5, waiting_cnt=0, berthed_cnt=7, updated_at=now() where name_en='Durban';
update public.pi_ports set tpfs=58.5, delay_h=21.5, waiting_cnt=0, berthed_cnt=3, updated_at=now() where name_en='Cape Town';
update public.pi_ports set tpfs=35.9, delay_h=10.3, waiting_cnt=0, berthed_cnt=5, updated_at=now() where name_en='Lagos (Apapa)';
update public.pi_ports set tpfs=41.5, delay_h=12.8, waiting_cnt=0, berthed_cnt=4, updated_at=now() where name_en='Mombasa';
update public.pi_ports set tpfs=45.2, delay_h=14.6, waiting_cnt=0, berthed_cnt=3, updated_at=now() where name_en='Dar es Salaam';
update public.pi_ports set tpfs=49.8, delay_h=16.9, waiting_cnt=0, berthed_cnt=4, updated_at=now() where name_en='Sydney (Botany)';
update public.pi_ports set tpfs=43.8, delay_h=13.9, waiting_cnt=0, berthed_cnt=6, updated_at=now() where name_en='Melbourne';
update public.pi_ports set tpfs=95.2, delay_h=44.6, waiting_cnt=3, berthed_cnt=8, updated_at=now() where name_en='Brisbane';
update public.pi_ports set tpfs=96.1, delay_h=45.2, waiting_cnt=1, berthed_cnt=3, updated_at=now() where name_en='Auckland';
update public.pi_snapshot set total_ports=93, tpfs=40.3, critical_ports=10, global_risk='MEDIUM', avg_delay_h=13.9, distribution='[{"level": "LOW", "ratio": 29.0, "count": 27, "delta": 0}, {"level": "STABLE", "ratio": 38.7, "count": 36, "delta": 0}, {"level": "BUSY", "ratio": 21.5, "count": 20, "delta": 0}, {"level": "CONGESTED", "ratio": 10.8, "count": 10, "delta": 0}]'::jsonb, period_start='2026-07-11', period_end='2026-07-17', updated_at=now() where id=1;