-- 자동 생성: collect_portinsight_api.py --sql (IMF PortWatch, 기준일 2026-07-24, 93개 항만)
update public.pi_ports set tpfs=27.7, delay_h=7.0, waiting_cnt=0, berthed_cnt=85, updated_at=now() where name_en='Shanghai';
update public.pi_ports set tpfs=74.0, delay_h=30.6, waiting_cnt=11, berthed_cnt=56, updated_at=now() where name_en='Ningbo';
update public.pi_ports set tpfs=4.1, delay_h=0.4, waiting_cnt=0, berthed_cnt=9, updated_at=now() where name_en='Shenzhen (Yantian)';
update public.pi_ports set tpfs=55.6, delay_h=19.9, waiting_cnt=1, berthed_cnt=30, updated_at=now() where name_en='Guangzhou (Nansha)';
update public.pi_ports set tpfs=34.6, delay_h=9.8, waiting_cnt=0, berthed_cnt=29, updated_at=now() where name_en='Qingdao';
update public.pi_ports set tpfs=48.8, delay_h=16.4, waiting_cnt=0, berthed_cnt=30, updated_at=now() where name_en='Tianjin';
update public.pi_ports set tpfs=15.5, delay_h=2.9, waiting_cnt=0, berthed_cnt=17, updated_at=now() where name_en='Xiamen';
update public.pi_ports set tpfs=96.9, delay_h=45.8, waiting_cnt=9, berthed_cnt=23, updated_at=now() where name_en='Dalian';
update public.pi_ports set tpfs=33.0, delay_h=9.1, waiting_cnt=0, berthed_cnt=38, updated_at=now() where name_en='Hong Kong';
update public.pi_ports set tpfs=48.6, delay_h=16.3, waiting_cnt=0, berthed_cnt=29, updated_at=now() where name_en='Kaohsiung';
update public.pi_ports set tpfs=79.3, delay_h=33.9, waiting_cnt=9, berthed_cnt=15, updated_at=now() where name_en='Busan';
update public.pi_ports set tpfs=77.0, delay_h=32.4, waiting_cnt=1, berthed_cnt=2, updated_at=now() where name_en='Incheon';
update public.pi_ports set tpfs=68.8, delay_h=27.4, waiting_cnt=3, berthed_cnt=1, updated_at=now() where name_en='Gwangyang';
update public.pi_ports set tpfs=76.8, delay_h=32.3, waiting_cnt=6, berthed_cnt=27, updated_at=now() where name_en='Tokyo';
update public.pi_ports set tpfs=67.1, delay_h=26.4, waiting_cnt=5, berthed_cnt=40, updated_at=now() where name_en='Yokohama';
update public.pi_ports set tpfs=70.7, delay_h=28.5, waiting_cnt=8, berthed_cnt=46, updated_at=now() where name_en='Nagoya';
update public.pi_ports set tpfs=75.2, delay_h=31.3, waiting_cnt=6, berthed_cnt=31, updated_at=now() where name_en='Kobe';
update public.pi_ports set tpfs=12.7, delay_h=2.2, waiting_cnt=0, berthed_cnt=115, updated_at=now() where name_en='Singapore';
update public.pi_ports set tpfs=28.4, delay_h=7.3, waiting_cnt=0, berthed_cnt=12, updated_at=now() where name_en='Tanjung Pelepas';
update public.pi_ports set tpfs=30.1, delay_h=7.9, waiting_cnt=0, berthed_cnt=32, updated_at=now() where name_en='Port Klang';
update public.pi_ports set tpfs=64.2, delay_h=24.7, waiting_cnt=1, berthed_cnt=5, updated_at=now() where name_en='Penang';
update public.pi_ports set tpfs=71.4, delay_h=29.0, waiting_cnt=1, berthed_cnt=3, updated_at=now() where name_en='Kuching';
update public.pi_ports set tpfs=25.5, delay_h=6.2, waiting_cnt=0, berthed_cnt=26, updated_at=now() where name_en='Jakarta (Tg. Priok)';
update public.pi_ports set tpfs=37.6, delay_h=11.1, waiting_cnt=0, berthed_cnt=17, updated_at=now() where name_en='Surabaya';
update public.pi_ports set tpfs=18.9, delay_h=3.9, waiting_cnt=0, berthed_cnt=19, updated_at=now() where name_en='Laem Chabang';
update public.pi_ports set tpfs=28.8, delay_h=7.4, waiting_cnt=0, berthed_cnt=19, updated_at=now() where name_en='Bangkok';
update public.pi_ports set tpfs=51.4, delay_h=17.7, waiting_cnt=0, berthed_cnt=13, updated_at=now() where name_en='Ho Chi Minh (Cat Lai)';
update public.pi_ports set tpfs=60.7, delay_h=22.7, waiting_cnt=1, berthed_cnt=16, updated_at=now() where name_en='Cai Mep';
update public.pi_ports set tpfs=51.7, delay_h=17.8, waiting_cnt=0, berthed_cnt=22, updated_at=now() where name_en='Haiphong';
update public.pi_ports set tpfs=87.3, delay_h=39.2, waiting_cnt=7, berthed_cnt=22, updated_at=now() where name_en='Manila';
update public.pi_ports set tpfs=31.6, delay_h=8.5, waiting_cnt=0, berthed_cnt=4, updated_at=now() where name_en='Yangon';
update public.pi_ports set tpfs=59.7, delay_h=22.1, waiting_cnt=0, berthed_cnt=4, updated_at=now() where name_en='Sihanoukville';
update public.pi_ports set tpfs=26.0, delay_h=6.4, waiting_cnt=0, berthed_cnt=11, updated_at=now() where name_en='Colombo';
update public.pi_ports set tpfs=32.8, delay_h=9.0, waiting_cnt=0, berthed_cnt=6, updated_at=now() where name_en='Chattogram';
update public.pi_ports set tpfs=31.1, delay_h=8.3, waiting_cnt=0, berthed_cnt=22, updated_at=now() where name_en='Nhava Sheva (JNPT)';
update public.pi_ports set tpfs=27.4, delay_h=6.9, waiting_cnt=0, berthed_cnt=9, updated_at=now() where name_en='Mundra';
update public.pi_ports set tpfs=69.0, delay_h=27.5, waiting_cnt=1, berthed_cnt=4, updated_at=now() where name_en='Chennai';
update public.pi_ports set tpfs=45.0, delay_h=14.5, waiting_cnt=0, berthed_cnt=5, updated_at=now() where name_en='Karachi';
update public.pi_ports set tpfs=60.3, delay_h=22.5, waiting_cnt=0, berthed_cnt=5, updated_at=now() where name_en='Jebel Ali';
update public.pi_ports set tpfs=36.5, delay_h=10.6, waiting_cnt=0, berthed_cnt=1, updated_at=now() where name_en='Khalifa (Abu Dhabi)';
update public.pi_ports set tpfs=8.9, delay_h=1.3, waiting_cnt=0, berthed_cnt=1, updated_at=now() where name_en='Hamad';
update public.pi_ports set tpfs=47.6, delay_h=15.8, waiting_cnt=0, berthed_cnt=2, updated_at=now() where name_en='Dammam';
update public.pi_ports set tpfs=67.8, delay_h=26.8, waiting_cnt=1, berthed_cnt=10, updated_at=now() where name_en='Jeddah';
update public.pi_ports set tpfs=55.5, delay_h=19.8, waiting_cnt=0, berthed_cnt=6, updated_at=now() where name_en='Salalah';
update public.pi_ports set tpfs=74.5, delay_h=30.9, waiting_cnt=0, berthed_cnt=1, updated_at=now() where name_en='Bandar Abbas';
update public.pi_ports set tpfs=79.7, delay_h=34.2, waiting_cnt=21, berthed_cnt=89, updated_at=now() where name_en='Rotterdam';
update public.pi_ports set tpfs=34.8, delay_h=9.9, waiting_cnt=0, berthed_cnt=54, updated_at=now() where name_en='Antwerp-Bruges';
update public.pi_ports set tpfs=30.3, delay_h=8.0, waiting_cnt=0, berthed_cnt=17, updated_at=now() where name_en='Hamburg';
update public.pi_ports set tpfs=46.9, delay_h=15.4, waiting_cnt=0, berthed_cnt=12, updated_at=now() where name_en='Bremerhaven';
update public.pi_ports set tpfs=43.8, delay_h=13.9, waiting_cnt=0, berthed_cnt=10, updated_at=now() where name_en='Le Havre';
update public.pi_ports set tpfs=67.0, delay_h=26.3, waiting_cnt=1, berthed_cnt=4, updated_at=now() where name_en='Fos-Marseille';
update public.pi_ports set tpfs=28.9, delay_h=7.5, waiting_cnt=0, berthed_cnt=10, updated_at=now() where name_en='Valencia';
update public.pi_ports set tpfs=28.6, delay_h=7.3, waiting_cnt=0, berthed_cnt=16, updated_at=now() where name_en='Algeciras';
update public.pi_ports set tpfs=8.1, delay_h=1.1, waiting_cnt=0, berthed_cnt=10, updated_at=now() where name_en='Barcelona';
update public.pi_ports set tpfs=22.2, delay_h=5.0, waiting_cnt=0, berthed_cnt=8, updated_at=now() where name_en='Genoa';
update public.pi_ports set tpfs=58.3, delay_h=21.4, waiting_cnt=0, berthed_cnt=6, updated_at=now() where name_en='Gioia Tauro';
update public.pi_ports set tpfs=36.1, delay_h=10.4, waiting_cnt=0, berthed_cnt=5, updated_at=now() where name_en='Trieste';
update public.pi_ports set tpfs=54.8, delay_h=19.5, waiting_cnt=0, berthed_cnt=3, updated_at=now() where name_en='Koper';
update public.pi_ports set tpfs=44.0, delay_h=14.0, waiting_cnt=0, berthed_cnt=14, updated_at=now() where name_en='Piraeus';
update public.pi_ports set tpfs=56.5, delay_h=20.4, waiting_cnt=1, berthed_cnt=11, updated_at=now() where name_en='Ambarli (Istanbul)';
update public.pi_ports set tpfs=42.5, delay_h=13.3, waiting_cnt=0, berthed_cnt=8, updated_at=now() where name_en='Mersin';
update public.pi_ports set tpfs=72.0, delay_h=29.3, waiting_cnt=2, berthed_cnt=10, updated_at=now() where name_en='Gdansk';
update public.pi_ports set tpfs=26.1, delay_h=6.4, waiting_cnt=0, berthed_cnt=3, updated_at=now() where name_en='Felixstowe';
update public.pi_ports set tpfs=93.9, delay_h=43.7, waiting_cnt=2, berthed_cnt=7, updated_at=now() where name_en='London Gateway';
update public.pi_ports set tpfs=40.8, delay_h=12.5, waiting_cnt=0, berthed_cnt=10, updated_at=now() where name_en='Los Angeles';
update public.pi_ports set tpfs=40.8, delay_h=12.5, waiting_cnt=0, berthed_cnt=10, updated_at=now() where name_en='Long Beach';
update public.pi_ports set tpfs=96.3, delay_h=45.4, waiting_cnt=1, berthed_cnt=3, updated_at=now() where name_en='Oakland';
update public.pi_ports set tpfs=14.1, delay_h=2.5, waiting_cnt=0, berthed_cnt=1, updated_at=now() where name_en='Seattle-Tacoma';
update public.pi_ports set tpfs=41.0, delay_h=12.6, waiting_cnt=0, berthed_cnt=6, updated_at=now() where name_en='Vancouver';
update public.pi_ports set tpfs=63.8, delay_h=24.5, waiting_cnt=1, berthed_cnt=11, updated_at=now() where name_en='New York/New Jersey';
update public.pi_ports set tpfs=42.9, delay_h=13.5, waiting_cnt=0, berthed_cnt=6, updated_at=now() where name_en='Savannah';
update public.pi_ports set tpfs=32.9, delay_h=9.1, waiting_cnt=0, berthed_cnt=4, updated_at=now() where name_en='Charleston';
update public.pi_ports set tpfs=45.7, delay_h=14.8, waiting_cnt=0, berthed_cnt=21, updated_at=now() where name_en='Houston';
update public.pi_ports set tpfs=66.1, delay_h=25.8, waiting_cnt=1, berthed_cnt=5, updated_at=now() where name_en='Manzanillo (MX)';
update public.pi_ports set tpfs=35.5, delay_h=10.2, waiting_cnt=0, berthed_cnt=5, updated_at=now() where name_en='Lazaro Cardenas';
update public.pi_ports set tpfs=14.1, delay_h=2.5, waiting_cnt=0, berthed_cnt=14, updated_at=now() where name_en='Santos';
update public.pi_ports set tpfs=10.0, delay_h=1.5, waiting_cnt=0, berthed_cnt=5, updated_at=now() where name_en='Callao';
update public.pi_ports set tpfs=7.6, delay_h=1.0, waiting_cnt=0, berthed_cnt=10, updated_at=now() where name_en='Cartagena';
update public.pi_ports set tpfs=9.4, delay_h=1.4, waiting_cnt=0, berthed_cnt=3, updated_at=now() where name_en='Colon (Panama)';
update public.pi_ports set tpfs=57.2, delay_h=20.8, waiting_cnt=0, berthed_cnt=4, updated_at=now() where name_en='Buenos Aires';
update public.pi_ports set tpfs=69.4, delay_h=27.8, waiting_cnt=1, berthed_cnt=6, updated_at=now() where name_en='Guayaquil';
update public.pi_ports set tpfs=71.4, delay_h=29.0, waiting_cnt=2, berthed_cnt=13, updated_at=now() where name_en='Tanger Med';
update public.pi_ports set tpfs=65.0, delay_h=25.2, waiting_cnt=0, berthed_cnt=2, updated_at=now() where name_en='Port Said';
update public.pi_ports set tpfs=43.9, delay_h=14.0, waiting_cnt=0, berthed_cnt=9, updated_at=now() where name_en='Alexandria';
update public.pi_ports set tpfs=14.3, delay_h=2.6, waiting_cnt=0, berthed_cnt=6, updated_at=now() where name_en='Durban';
update public.pi_ports set tpfs=4.4, delay_h=0.4, waiting_cnt=0, berthed_cnt=2, updated_at=now() where name_en='Cape Town';
update public.pi_ports set tpfs=71.1, delay_h=28.8, waiting_cnt=1, berthed_cnt=6, updated_at=now() where name_en='Lagos (Apapa)';
update public.pi_ports set tpfs=78.8, delay_h=33.6, waiting_cnt=1, berthed_cnt=5, updated_at=now() where name_en='Mombasa';
update public.pi_ports set tpfs=78.6, delay_h=33.4, waiting_cnt=1, berthed_cnt=4, updated_at=now() where name_en='Dar es Salaam';
update public.pi_ports set tpfs=90.5, delay_h=41.3, waiting_cnt=2, berthed_cnt=5, updated_at=now() where name_en='Sydney (Botany)';
update public.pi_ports set tpfs=34.7, delay_h=9.8, waiting_cnt=0, berthed_cnt=5, updated_at=now() where name_en='Melbourne';
update public.pi_ports set tpfs=7.5, delay_h=1.0, waiting_cnt=0, berthed_cnt=6, updated_at=now() where name_en='Brisbane';
update public.pi_ports set tpfs=38.5, delay_h=11.5, waiting_cnt=0, berthed_cnt=2, updated_at=now() where name_en='Auckland';
update public.pi_snapshot set total_ports=93, tpfs=46.8, critical_ports=12, global_risk='MEDIUM', avg_delay_h=16.9, distribution='[{"level": "LOW", "ratio": 16.1, "count": 15, "delta": -12}, {"level": "STABLE", "ratio": 40.9, "count": 38, "delta": 2}, {"level": "BUSY", "ratio": 30.1, "count": 28, "delta": 8}, {"level": "CONGESTED", "ratio": 12.9, "count": 12, "delta": 2}]'::jsonb, period_start='2026-07-18', period_end='2026-07-24', updated_at=now() where id=1;